
services:

  server:
    build: .
    volumes:
      - source:/projeto
    command: /bin/bash
    tty: true
  
  client:
    build: .
    volumes:
      - source:/projeto
    command: /bin/bash
    tty: true

volumes:
  source:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/michel/Documents/GitHub/energy-ros2-cpp-python/